:logfile: ./log/sidekiq.log

:concurrency: 3

:pidfile: tmp/pids/sidekiq.pid

:max_retries: 10

:limits:
  data_operations: 1
  web_hooks: 1
  ahoy: 1
:queues:
  - cc_homes_data_operations
  - cc_homes_web_hooks
  - ahoy
  - default
